name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate summary cards

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Daemon-AT4
          BRANCH_NAME: profile-summary-card-output
          THEME: github_dark
